### ISSUE TITLE
Basic configuration

### ISSUE THREAD

**Issue by ramcourse** [luebking/sqriptor#3]
I like sqriptor, but to make it a go-to text editor, I need to be able to do some basic configuration that the competition already has. Things like:

- when opening a txt file, I want the window to open to a certain size from the start, instead of having to resize the window manually every time
- word wrap status is not 'remembered' from last time when the program opens
- the 80 character line is useful sometimes, but being able to configure it [like the 7-72 char limit for old Fortran] or to be able to switch it off would be even more useful
- being able to do all this configuration in a text file would be great, if only to be able to experiment with settings while keeping a backup of the setup.

The project resonates with me, but the integration in my workflow isn't quite doable yet.

Thank you for your attention to this matter.

**Comment by luebking** [comment]
You can configure a textfile (~/.config/sqriptor.conf) but adding "hidden" features this way isn't a good approach - you're creating pet peeving secrets as illustrated by the fact that there was already a config key for the size (for debugging only)
:P

If you file future bug reports or feature requests, please feel free to create one issue per item instead of a shopping list.
It's not a problem in this case because none of the requests is really controversial and it's not a lot of code either, but in general one issue per item is more maintainable (eg. if you file 3 bugs and I can fix one immediately, struggle w/ the second and don't really consider the 3rd a bug, how do I treat the issue?)

In case you should wonder - word wrapping isn't remembered but there's a dedicated setting that's augmented by the menu item (kinda like the tab mode thing)

**Comment by ramcourse** [comment]
Thanks, still finding my way around this system. Didn't want to spam your issue list.
How do I set up this config file?

**Comment by luebking** [comment]
There's actually a config GUI for the additions under View/Settings…/Feel

**Comment by ramcourse** [comment]
View/Settings/Feel only gives me this:
![sqriptorFeel](https://user-images.githubusercontent.com/96936957/147889546-9524efe2-e939-405e-9ab6-4cca1983e9f4.jpg)

**Comment by luebking** [comment]
Did you "git pull" and rebuild sqriptor?

**Comment by ramcourse** [comment]
I did now!
The settings are there now, and seem to work well. Thanks!
